name: DankTech2
author: Sefiraat
contributors: [wickidcow]
description: An addon to Slimefun that adds mass-storage backpacks.
main: io.github.sefiraat.danktech2.DankTech2
website: https://github.com/wickidcow/DankTech2
version: ${project.version}
api-version: '1.21'
depend:
  - Slimefun
softdepend:
  - mcMMO
  - RoseStacker
  - WildStacker
commands:
  danktech2:
    description: /danktech2
    usage: /danktech2 <sub>
    aliases: [dt, dank]
